// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package balance

import (
	"github.com/high-performance-payment-gateway/order-service/order/application"
	"github.com/high-performance-payment-gateway/order-service/order/domain/query/order_query"
)

// Injectors from wire.go:

func ProviderService() application.ServiceInterface {
	oneRequestInterface := order_query.NewOneRequest()
	allPartnerBalanceQuery := application.NewAllPartnerBalanceQuery(oneRequestInterface)
	service := application.NewService(allPartnerBalanceQuery)
	return service
}
